name: "FiatUconnect"
url: "https://github.com/AirBeeSee/FiatUconnect"
description: "Connect your FIAT (uconnect) car to Home Assistant. 🚗"
services:
    - "mqtt:want"
version: "9.0.3"
homeassistant_api: true
image: "ghcr.io/airbeesee/image-{arch}-fiat-uconnect"
slug: "fiat_uconnect"
init: false
discovery: 
    - "mqtt"
options:
  FiatUser: ""
  FiatPw: ""
  FiatPin: ""

  RefreshInterval: 2
  Debug: false
  AutoDeepRefresh: false
  AutoDeepInterval: 15

  StartDelaySeconds: 2
schema:
  FiatUser: str
  FiatPw: password
  FiatPin: password?
  RefreshInterval: int
  Debug: bool
  AutoDeepRefresh: bool
  AutoDeepInterval: int
  StartDelaySeconds: int?
arch:
  - amd64
  - armv7  

