name: "FiatUconnect"
url: "https://github.com/AirBeeSee/FiatUconnect"
description: "Connect your FIAT (uconnect) car to Home Assistant. 🚗"
services:
    - "mqtt:want"
version: "10.0.7"
homeassistant_api: true
image: "ghcr.io/airbeesee/image-{arch}-fiat-uconnect"
slug: "fiat_uconnect"
init: false
discovery: 
    - "mqtt"
options:
  FiatUser: ""
  FiatPw: ""
  FiatPin: ""

  Brand: "Fiat"
  Region: "Europe"
  
  RefreshInterval: 2
  Debug: false
  AutoDeepRefresh: false
  AutoDeepInterval: 15

  StartDelaySeconds: 2
schema:
  FiatUser: str
  FiatPw: password
  FiatPin: password?

  Brand: list(Fiat|Ram|Jeep|Dodge|AlfaRomeo|Debug)
  Region: list(Europe|US)
  
  RefreshInterval: int
  Debug: bool
  AutoDeepRefresh: bool
  AutoDeepInterval: int
  StartDelaySeconds: int?
arch:
  - amd64
  - armv7  

