name: "FiatUconnect"
url: "https://github.com/AirBeeSee/FiatUconnect"
description: "Connect your FIAT (uconnect) car to Home Assistant. 🚗"
services:
    - "mqtt:want"
version: "5.0.23"
homeassistant_api: true
image: "ghcr.io/airbeesee/image-{arch}-fiat-uconnect"
slug: "fiat_uconnect"
init: false
discovery: 
    - "mqtt"
options:
  FiatUser: ""
  FiatPw: ""
  FiatPin: ""

  RefreshInterval: 15
  Debug: false

  StartDelaySeconds: 2
schema:
  FiatUser: str
  FiatPw: password
  FiatPin: password?
  RefreshInterval: int
  Debug: bool
  StartDelaySeconds: int?
arch:
  - amd64

